#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.14f1_49dd4e9fa428"
#define UNITY_VERSION_FULL_NICE "2019.2.14f1 (49dd4e9fa428)"
#define UNITY_VERSION_BLD 4840782
#define UNITY_VERSION_DATE 1574249281
#define UNITY_VERSION_WIN "2019.2.14.4840782"
#define UNITY_VERSION_BRANCH "2019.2/staging"
